### ISSUE TITLE
Vercel.json 

### ISSUE THREAD

**Issue by ghost** [Yonle/go-bwhero#1]
What to write in vercel.json? Also make a detailed instructions for githubcodespace i do not want dockerfiles. Also please make a solution for govips installation failure.

**Comment by Yonle** [comment]
There are no plan for making this to work in vercel nor GCS. You may need to use this in a real server instead.

For govips, You will need to ensure that libvips is installed on the system / container that you have.

**Comment by WorldWar1234** [comment]
See https://vercel.com/docs/functions/runtimes/go
@Yonle

**Comment by Yonle** [comment]
> See https://vercel.com/docs/functions/runtimes/go
> @Yonle 

Even so, I don't think it will work as the system need to have libvips installed, which i don't think vercel had.
